### ISSUE TITLE
_CastError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by andreyguenov** [vitoramaral10/excel_to_json#10]
In Flutter, when testing on MacOS, I get a` _CastError (Null check operator used on a null value)` error on line 18 in excel_to_json.dart. 

- I am using the latest Flutter
- I haven't made any edits to the code
- I am uploading a standard .xlsx that is not empty
- I use the provided example code. 

**Screenshots**
![2022-11-01 16 09 01](https://user-images.githubusercontent.com/6558274/199253162-9f8b41d1-be7c-49fd-be46-73572ba48e1d.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6

**Comment by vitoramaral10** [comment]
Hi, thanks for reporting.

I'm analyzing what happened and what I can do to fix it.

As soon as I have more information, I'll come back here.

**Comment by andreyguenov** [comment]
Thank you so much for taking a look. I really appreciate all the hard work
you've put into this. :-)

**Comment by andreyguenov** [comment]
Thank you for resolving this, @vitoramaral10 ! :-)
