### ISSUE TITLE
There is no image data I inserted in-cell

### ISSUE THREAD

**Issue by adaonder** [vitoramaral10/excel_to_json#12]
How do I get the image data I added inside the cell?

**Comment by vitoramaral10** [comment]
Hey, adaonder!

The plugin only converts plain text to json, ex: database export or CSV file. As these files do not have complexity in the data, it was not prepared for this.

Currently I don't have time to develop new features in this plugin, and I'm just putting my hands in the dough for corrections.

If you can help me with a solution I will be grateful to implement this plugin.
